#!/bin/bash
make clean
make nanodev5
make nanode328
#make lilypad
#make lilypad_resonator
#make pro8
#make pro16
#make pro20
#make diecimila
#make ng
make atmega328
#make atmega328_pro8
#make luminet

